# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpg',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content1', mezzanine.core.fields.RichTextField(verbose_name='Content1')),
                ('content2', mezzanine.core.fields.RichTextField(verbose_name='Content2')),
                ('image1', models.ImageField(upload_to='about')),
                ('image2', models.ImageField(upload_to='about')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(upload_to='employee')),
                ('signature', models.ImageField(upload_to='employee')),
                ('date_joined', models.DateField(default=datetime.date.today, verbose_name='Date joined')),
                ('bio', mezzanine.core.fields.RichTextField(verbose_name='Bio')),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.Aboutpg')),
            ],
        ),
    ]
