# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 14:42
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20150921_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='member_price',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Member Price'),
        ),
    ]
