# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 09:25
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160828_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='member_price',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='diamond_member_price_hkd',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diamond Member Price HKD'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='diamond_member_price_rmb',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diamond Member Price RMB'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='gold_member_price_hkd',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gold Member Price HKD'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='gold_member_price_rmb',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gold Member Price RMB'),
        ),
    ]
