# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20160830_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Shipping URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='frontpage',
            field=models.BooleanField(default=False, verbose_name='Display on Front Page'),
        ),
        migrations.AddField(
            model_name='product',
            name='shoppage',
            field=models.BooleanField(default=False, verbose_name='Display on Shop Page'),
        ),
    ]
