# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-26 10:29
from __future__ import unicode_literals

import cartridge.shop.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20161205_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='price_hkd',
            field=cartridge.shop.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price HKD'),
        ),
    ]
