# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productvariation_price_hkd'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_membership_level',
            field=models.BooleanField(default=False, verbose_name='Is Membership'),
        ),
    ]
