# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productvariation_is_membership_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='is_membership_level',
        ),
        migrations.AddField(
            model_name='product',
            name='is_membership_level',
            field=models.BooleanField(default=False, verbose_name='Is Membership'),
        ),
    ]
