# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170130_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='membership_level',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Membership Level'),
        ),
    ]
