# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_discountcode_membership_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_class',
            field=models.BooleanField(default=False, verbose_name='Is Class'),
        ),
    ]
