# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-23 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_is_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_fortune',
            field=models.BooleanField(default=False, verbose_name='Is Fortune'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoppage',
            field=models.BooleanField(default=False, verbose_name='Display on Shop Large Image Slider'),
        ),
    ]
