# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-18 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoppage',
        ),
    ]
