# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-18 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_remove_product_shoppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frontbanner',
            field=models.BooleanField(default=False, verbose_name='Display on Shop Large Image Slider'),
        ),
    ]
