# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170611_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sold',
            field=models.IntegerField(default=0, verbose_name='Number Sold'),
        ),
    ]
