# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-18 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_product_shoppage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shoppage',
            field=models.BooleanField(default=False, verbose_name='Display product on Shop Page banner'),
        ),
    ]
