# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-23 11:40
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image'),
        ),
    ]
