# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-24 11:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Source ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Source Object'),
        ),
    ]
