# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-30 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20170724_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='membership_level',
            field=models.CharField(blank=True, choices=[('gold', 'gold'), ('diamond', 'diamond')], max_length=255, null=True, verbose_name='Membership Level'),
        ),
    ]
