# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-18 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20170730_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('class', 'Class'), ('fortune', 'Fortune'), ('numerology', 'Numerology'), ('membership', 'Membership')], default=('regular', 'Regular'), max_length=255, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='membership_level',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('diamond', 'diamond')], max_length=255, null=True, verbose_name='Membership Level'),
        ),
    ]
