# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-18 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20170818_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='membership_level',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('gold', 'Gold'), ('diamond', 'diamond')], max_length=255, null=True, verbose_name='Membership Level'),
        ),
    ]
