# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-18 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_auto_20170818_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frontbanner',
            field=models.BooleanField(default=False, verbose_name='Display on home slider'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frontpage',
            field=models.BooleanField(default=False, verbose_name='Display on home products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('class', 'Class'), ('fortune', 'Fortune'), ('prayer', 'Prayer'), ('numerology', 'Numerology'), ('membership', 'Membership')], default=('regular', 'Regular'), max_length=255, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoppage',
            field=models.BooleanField(default=False, verbose_name='Display product on shop page slider'),
        ),
    ]
