# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-18 09:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20170818_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Order paid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Stripe Source ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_obj',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Stripe Source Object'),
        ),
    ]
