# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 10:33
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content2',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content 2'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content3',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content 3'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content4',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content 4'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content5',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content 5'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image3',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image4',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image 4'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image5',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image 5'),
        ),
    ]
