# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-27 04:54
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160816_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content6',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Content 6'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image6',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image 6'),
        ),
    ]
