# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170327_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='frontbanner',
            field=models.BooleanField(default=False, verbose_name='Display on Front Page Banner'),
        ),
    ]
