# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpost_frontbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogpage',
            field=models.BooleanField(default=False, verbose_name='Display on Blog Page'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='frontpage',
            field=models.BooleanField(default=False, verbose_name='Feature on Front Page'),
        ),
    ]
