# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160707_0243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shipping_detail_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shipping_detail_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shipping_detail_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip/Postcode'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shipping_detail_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State/Region'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='shipping_detail_street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
