# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20160728_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_end', models.DateTimeField(auto_now_add=True, verbose_name='End Date')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('level', models.CharField(choices=[('regular', 'Regular'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='regular', max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
