# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 1, 8, 36, 22, 369537, tzinfo=utc), verbose_name='Member Since'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
