# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160901_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='member_since',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
