# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160902_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
