# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_membership_auto_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.CharField(choices=[('regular', 'Regular'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='regular', max_length=120),
        ),
    ]
