# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20161205_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 30, 13, 10, 37, 432197), verbose_name='Joined Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.CharField(choices=[('regular', 'Regular'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='regular', max_length=120),
        ),
    ]
