# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 09:04
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20170130_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='tasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, null=True, size=None),
        ),
    ]
