# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-27 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_membership_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='direction_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direction of Primary Location'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='direction_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direction of Secondary Location'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='direction_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direction of Third Location'),
        ),
    ]
