# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-03 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20170627_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile phone number'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='phone',
            field=models.CharField(default=18888888888, max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
