# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
